// gentux rasterizes the Font Awesome "linux" (Tux) glyph into a grayscale
// coverage mask and writes it as Go source (../../tuxmask.go), so the tray app
// itself needs no vector rasterizer or font at runtime.
//
//	cd tools/gentux && go run .
package main

import (
	"fmt"
	"image"
	"math"
	"os"
	"regexp"
	"strconv"
	"strings"

	"golang.org/x/image/vector"
)

const (
	maskH      = 128 // glyph height in pixels before cropping; width follows the viewBox aspect
	strokeGrow = 3   // dilation radius in mask pixels
	viewBoxW   = 448.0
	viewBoxH   = 512.0
)

func main() {
	svg, err := os.ReadFile("linux.svg")
	if err != nil {
		panic(err)
	}
	d := regexp.MustCompile(`d="([^"]*)"`).FindSubmatch(svg)[1]

	// Rasterize onto a canvas with a margin so the dilation below has room.
	const pad = 8
	maskW := int(math.Round(float64(maskH) * viewBoxW / viewBoxH))
	cw, ch := maskW+2*pad, maskH+2*pad
	scale := float64(maskH) / viewBoxH
	r := vector.NewRasterizer(cw, ch)
	walkPath(string(d), scale, pad, r)
	full := image.NewAlpha(image.Rect(0, 0, cw, ch))
	r.Draw(full, full.Bounds(), image.Opaque, image.Point{})

	// Holes = transparent pixels not reachable from the border (belly, face).
	fullHoles := findHoles(full.Pix, cw, ch)
	// Thicken the strokes a little: the glyph's outline is ~1 px at 24 px tray
	// size, which looks wispy next to the taskbar's bold text.
	fullMask := dilate(full.Pix, cw, ch, strokeGrow)
	for i := range fullHoles {
		if fullMask[i] >= 128 {
			fullHoles[i] = 0
		}
	}

	// Crop to the glyph's bounding box so the icon uses its whole height.
	bb := image.Rectangle{Min: image.Pt(cw, ch)}
	for y := 0; y < ch; y++ {
		for x := 0; x < cw; x++ {
			if fullMask[y*cw+x] > 0 {
				bb = bb.Union(image.Rect(x, y, x+1, y+1))
			}
		}
	}
	w, h := bb.Dx(), bb.Dy()
	mask := make([]byte, w*h)
	holes := make([]byte, w*h)
	for y := 0; y < h; y++ {
		src := (bb.Min.Y+y)*cw + bb.Min.X
		copy(mask[y*w:(y+1)*w], fullMask[src:src+w])
		copy(holes[y*w:(y+1)*w], fullHoles[src:src+w])
	}

	var b strings.Builder
	b.WriteString("// Code generated by tools/gentux; DO NOT EDIT.\n\n")
	b.WriteString("//go:build windows\n\npackage main\n\n")
	b.WriteString("// Tux silhouette: Font Awesome Free 6.5.1 \"linux\" icon, CC BY 4.0\n")
	b.WriteString("// (https://fontawesome.com/license/free), rasterized to a coverage mask.\n")
	b.WriteString("// tuxHoles marks the enclosed transparent areas (belly, face).\n")
	fmt.Fprintf(&b, "const tuxMaskW, tuxMaskH = %d, %d\n", w, h)
	writeBytes(&b, "tuxMask", mask)
	writeBytes(&b, "tuxHoles", holes)
	if err := os.WriteFile("../../tuxmask.go", []byte(b.String()), 0o644); err != nil {
		panic(err)
	}
	fmt.Printf("wrote tuxmask.go (%dx%d)\n", w, h)
}

func writeBytes(b *strings.Builder, name string, data []byte) {
	fmt.Fprintf(b, "\nvar %s = []byte{", name)
	for i, v := range data {
		if i%32 == 0 {
			b.WriteString("\n\t")
		}
		fmt.Fprintf(b, "%d,", v)
	}
	b.WriteString("\n}\n")
}

// dilate grows coverage by taking the max over a disc of radius r.
func dilate(mask []byte, w, h, r int) []byte {
	out := make([]byte, len(mask))
	for y := 0; y < h; y++ {
		for x := 0; x < w; x++ {
			var m byte
			for dy := -r; dy <= r; dy++ {
				for dx := -r; dx <= r; dx++ {
					if dx*dx+dy*dy > r*r {
						continue
					}
					xx, yy := x+dx, y+dy
					if xx < 0 || yy < 0 || xx >= w || yy >= h {
						continue
					}
					if v := mask[yy*w+xx]; v > m {
						m = v
					}
				}
			}
			out[y*w+x] = m
		}
	}
	return out
}

// findHoles flood-fills "outside" from the border through low-coverage pixels;
// whatever low-coverage pixels remain are enclosed holes (255 = hole).
func findHoles(mask []byte, w, h int) []byte {
	const solid = 128
	outside := make([]bool, w*h)
	stack := make([]int, 0, w*h)
	push := func(x, y int) {
		if x < 0 || y < 0 || x >= w || y >= h {
			return
		}
		i := y*w + x
		if outside[i] || mask[i] >= solid {
			return
		}
		outside[i] = true
		stack = append(stack, i)
	}
	for x := 0; x < w; x++ {
		push(x, 0)
		push(x, h-1)
	}
	for y := 0; y < h; y++ {
		push(0, y)
		push(w-1, y)
	}
	for len(stack) > 0 {
		i := stack[len(stack)-1]
		stack = stack[:len(stack)-1]
		x, y := i%w, i/w
		push(x-1, y)
		push(x+1, y)
		push(x, y-1)
		push(x, y+1)
	}
	holes := make([]byte, w*h)
	for i := range mask {
		if !outside[i] && mask[i] < solid {
			holes[i] = 255
		}
	}
	return holes
}

// walkPath feeds an SVG path (M/m, L/l, H/h, V/v, C/c, S/s, Z/z) into the rasterizer.
func walkPath(d string, k, off float64, r *vector.Rasterizer) {
	tok := regexp.MustCompile(`[MmLlHhVvCcSsZz]|-?\d*\.?\d+(?:e-?\d+)?`).FindAllString(d, -1)
	var cmd byte
	var cx, cy, sx, sy, lcx, lcy float64 // current point, subpath start, last control point
	num := func(i *int) float64 {
		v, _ := strconv.ParseFloat(tok[*i], 64)
		*i++
		return v
	}
	for i := 0; i < len(tok); {
		if t := tok[i]; len(t) == 1 && strings.ContainsAny(t, "MmLlHhVvCcSsZz") {
			cmd = t[0]
			i++
			if cmd == 'Z' || cmd == 'z' {
				r.ClosePath()
				cx, cy = sx, sy
				lcx, lcy = cx, cy
				continue
			}
		}
		rel := cmd >= 'a'
		switch cmd {
		case 'M', 'm':
			x, y := num(&i), num(&i)
			if rel {
				x, y = cx+x, cy+y
			}
			r.MoveTo(float32(x*k+off), float32(y*k+off))
			cx, cy, sx, sy = x, y, x, y
			if rel { // subsequent pairs are implicit LineTo

				cmd = 'l'
			} else {
				cmd = 'L'
			}
		case 'L', 'l':
			x, y := num(&i), num(&i)
			if rel {
				x, y = cx+x, cy+y
			}
			r.LineTo(float32(x*k+off), float32(y*k+off))
			cx, cy = x, y
		case 'H', 'h':
			x := num(&i)
			if rel {
				x += cx
			}
			r.LineTo(float32(x*k+off), float32(cy*k+off))
			cx = x
		case 'V', 'v':
			y := num(&i)
			if rel {
				y += cy
			}
			r.LineTo(float32(cx*k+off), float32(y*k+off))
			cy = y
		case 'C', 'c':
			x1, y1, x2, y2, x, y := num(&i), num(&i), num(&i), num(&i), num(&i), num(&i)
			if rel {
				x1, y1, x2, y2, x, y = cx+x1, cy+y1, cx+x2, cy+y2, cx+x, cy+y
			}
			r.CubeTo(float32(x1*k+off), float32(y1*k+off), float32(x2*k+off), float32(y2*k+off), float32(x*k+off), float32(y*k+off))
			lcx, lcy, cx, cy = x2, y2, x, y
		case 'S', 's':
			x2, y2, x, y := num(&i), num(&i), num(&i), num(&i)
			if rel {
				x2, y2, x, y = cx+x2, cy+y2, cx+x, cy+y
			}
			x1, y1 := 2*cx-lcx, 2*cy-lcy // reflection of previous control point
			r.CubeTo(float32(x1*k+off), float32(y1*k+off), float32(x2*k+off), float32(y2*k+off), float32(x*k+off), float32(y*k+off))
			lcx, lcy, cx, cy = x2, y2, x, y
		default:
			panic("unsupported path command " + string(cmd))
		}
		if cmd != 'C' && cmd != 'c' && cmd != 'S' && cmd != 's' {
			lcx, lcy = cx, cy
		}
	}
}
